version: "3"

services:

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  frontend:
    build: ../webworker-uploads/
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ../webworker-uploads:/usr/src/app

  backend:
    build: ../webworker-server
    environment:
      env_file: .env
      NODE_ENV: development
      DOCKER_ENV: 1
    ports:
      - '8081:8081'
    volumes:
      - ../webworker-server:/usr/src/app

  storage:
    depends_on:
      - mongo
    build: ../webworker-storage
    links:
      - mongo
    environment:
      env_file: .env
      NODE_ENV: development
      DOCKER_DB: 27107
    ports:
      - '8082:8082'
    volumes:
      - ../webworker-storage:/usr/src/app
