version: "3"

services:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  frontend:
    build: ../webworker-uploads/
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ../webworker-uploads:/usr/src/app

  backend:
    build: ../webworker-server
    environment:
      env_file: .env
      NODE_ENV: development
      DOCKER_ENV: 1
    ports:
      - '8081:8081'
    volumes:
      - ../webworker-server:/usr/src/app

  storage:
    depends_on:
      - mysql
    build: ../sequelize-playground
    links:
      - mysql
    environment:
      env_file: .env
      NODE_ENV: development
      DOCKER_DB: 27107
    ports:
      - '8082:8082'
    volumes:
      - ../sequelize-playground:/usr/src/app
